---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-k8s
  namespace: argo-helm-config
spec:
  chart:
    spec:
      chart: ./helm
      reconcileStrategy: ChartVersion
      valuesFiles:
       - ./helm/values-staging.yaml
      sourceRef:
        kind: GitRepository
        name: argo-helm-config
      version: '>0.0.0'
  interval: 3m0s

