---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argo-helm-config
  namespace: argo-helm-config
spec:
  interval: 1m0s
  # ignore: |
  #   /*
  #   !/helm/
  
  ref:
    semver:
  url: https://github.com/remotejob/argo-helm

