---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argo-helm-config
  namespace: argo-helm-config
spec:
  interval: 1m
  url: https://github.com/remotejob/argo-helm
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/ 


