namespace:
  name: prod

service:
  port: 4111
  targetPort: 5000
  protocol: TCP
  type: ClusterIP

image:
  repository: remotejob/hello-k8s
  tag: '5.0'
  pullPolicy: IfNotPresent

replicaCount: 5

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 5000
