namespace:
  name: prod

service:
  port: 6111
  
replicaCount: 6

image:
  tag: '5.0'
  pullPolicy: Always

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
