namespace:
  name: dev

service:
  port: 8111

image:
  tag: '0.0.0'
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi
